### PR TITLE
added seed data and fixed contact/page.tsx

### LINKED ISSUE #56: Additional Seed data
Currently just going to add 10 items so that there are more to utilize for testing etc.

### PR DESCRIPTION
**Pull request by LynchHarrison**
Some red lines just need to go away...

### CODE REVIEW

File: app/contact/page.tsx [hunk 1]
```diff
@@ -147,8 +147,8 @@ const ContactForm = () => {
             Contact Us
           </h1>
           <p className='text-gray-600 text-lg'>
-            We'd love to hear from you. Please fill out the
```
Comment (jameswonlee) [inline app/contact/page.tsx:150]: Thank you! :)

**Review by jameswonlee — APPROVED** [review]
Looks good!
